name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      - run: python3 -m unittest -v
      - name: Test SSH
        run: |
          sshpass -p "$SSH_PASSWORD" ssh \
          -o StrictHostKeyChecking=no \
          -o ConnectTimeout=10 \
          ubuntu@20.56.74.49 \
          "echo Connexion SSH OK"
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

      - name: Test SCP
        run: |
          sshpass -p "$SSH_PASSWORD" scp -v \
          -o StrictHostKeyChecking=no \
          test_addition.py \
          ubuntu@20.56.74.49:/home/ubuntu/CH/
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      - name: Check copied file
        run: |
          sshpass -p "$SSH_PASSWORD" ssh \
          -o StrictHostKeyChecking=no \
          ubuntu@20.56.74.49 \
          "ls -l /home/ubuntu/CH/test_addition.py"
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
