name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      - run: python3 -m unittest -v
      - run: sshpass -p "$SSH_PASSWORD" scp
