name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 test_addition.py
        env:
          SECRET_API_TOKEN: ${{ secrets.SECRET_API_TOKEN }}
      - run: echo "Contenu de mon fichier de test" > output.txt
      - uses: actions/upload-artifact@v4
        with:
          name: mon-fichier
          path: output.txt
